#!/usr/bin/env php

<?php

set_time_limit( 0 );

require __DIR__ . '/../bootstrap.php';

$bot = new Wikibot\Bot(
	__DIR__ . '/../config/config.yml',
	__DIR__ . '/../log'
);

$command = new DeployBot\Command\BranchInfoCommand();
$bot->registerCommand( $command );

$bot->run();
